logging.level:
  org.springframework: INFO
  io.edgerun.emma: DEBUG

emma.controller:
  address: 0
  heartbeat:
    port: 60042
  monitoring:
    port: 60043
  control:
    port: 60044
  shell:
    port: 50042
  redis:
    host: localhost
    port: 6379
